// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function $$default(props) {
  return React.createElement("div", undefined, React.createElement(Link, {
                  href: "/posts/1",
                  children: "Post 1"
                }), React.createElement(Link, {
                  href: "/posts/2",
                  children: "Post 2"
                }), props.msg);
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "Posts Page: ",
                href: "https://github.com/ryyppy/nextjs-default/tree/master/src/Examples.res"
              }
            });
}

var Link$1;

export {
  Link$1 as Link,
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
