// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Router from "next/router";

function $$default(props) {
  var router = Router.useRouter();
  var slug = Js_dict.get(router.query, "slug");
  return React.createElement("div", undefined, props.msg, React.createElement("a", {
                  href: props.href,
                  target: "_blank"
                }, "'/post/[" + slug + "] [slug].res'"));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "Post [slug] Page: ",
                href: "https://github.com/ryyppy/nextjs-default/tree/master/src/Examples.res"
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
